Live.Log.Extractor.Web/Controllers/CartController.cs
namespace Live.Log.Extractor.Web.Controllers
{
    using System.Web.Mvc;
    using Live.Log.Extractor.Web.Helper.Mappers;
    using Live.Log.Extractor.Web.Models;

    public class CartController : BaseController
    {
        /// <summary>
        /// Summaries this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Summary()
        {
            CartViewModel vm = new CartViewModel();
            Mapper.MapDataModelToCartViewModel(logDataModel, vm);
            return View(vm);
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Login");
        }

    }
}

Live.Log.Extractor.Web/Controllers/EDDController.cs
namespace Live.Log.Extractor.Web.Controllers
{
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data;
    using System.Linq;
    using System.Web.Mvc;
    using Live.Log.Extractor.Domain.ServiceHelper;
    using Live.Log.Extractor.Web.Helper.Attributes;
    using Live.Log.Extractor.Web.Helper.Mappers;
    using Live.Log.Extractor.Web.Models;
    using Live.Log.Extractor.Web.Helper;
    using Live.Log.Extractor.Domain;
    using System.IO;
    using Ionic.Zip;

    [AjaxSessionAttribute(SessionKey = sessionKey)]
    public class EDDController : BaseController
    {
        /// <summary>
        /// EDD view model.
        /// </summary>
        EDDViewModel vm;

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            vm = new EDDViewModel();   
            return View(vm);
        }

        /// <summary>
        /// Gets the EDDIO rows from policy number.
        /// </summary>
        /// <param name="Input">The input.</param>
        /// <param name="Region">The region.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEDDIORowsFromPolicyNumber(string Input, string Region)
        {
            this.vm = new EDDViewModel();

            vm.ExceedRegion.CurrentRegion = Region;
            vm.PolicyNumber = Input;
            vm.PolicyID = this.GetPolicyIDFromPolicyNumber();
            if (!string.IsNullOrEmpty(vm.PolicyID))
            {
                List<EDDIORow> eDDIORows = this.CreateEDDIORows();
                if (eDDIORows != null && eDDIORows.Count > 0)
                {
                    var formattedData = new { EDDRows = eDDIORows };
                    return Json(formattedData);
                }
                else
                {
                    return this.DataNotFound("No Data found for this Policy Number.");
                }
            }
            else
            {
                return this.DataNotFound("No Data found for this Policy Number.");
            }
        }

        /// <summary>
        /// Gets the EDDIO rows from polic ID.
        /// </summary>
        /// <param name="Input">The input.</param>
        /// <param name="Region">The region.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEDDIORowsFromPolicID(string Input, string Region)
        {
            this.vm = new EDDViewModel();

            vm.ExceedRegion.CurrentRegion = Region;
            vm.PolicyID = Input;

            this.logDataModel.EddKeys = this.CreateEDDIORows();

            if (this.logDataModel.EddKeys != null && this.logDataModel.EddKeys.Count > 0)
            {
                var formattedData = new { EDDRows = this.logDataModel.EddKeys };
                return Json(formattedData);
            }
            else
            {
                return this.DataNotFound("No Data found for this Policy ID.");
            }
        }

        /// <summary>
        /// Gets the EDD message.
        /// </summary>
        /// <param name="Input">The input.</param>
        /// <param name="Region">The region.</param>
        /// <param name="IsPolicyID">if set to <c>true</c> [is policy ID].</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEDDMessage(string Input, string Region, bool IsPolicyID)
        {
            this.vm = new EDDViewModel();
            if (string.IsNullOrEmpty(Input) || !ModelState.IsValid)
            {
                return View(vm);
            }

            vm.EddKey = Input;
            Mapper.MapEDDKeyToDataModel(vm, this.logDataModel);
            string EDDMessage = this.CreateEDDMessage();
            var formattedData = new { EDDMessage = EDDMessage.Replace("|", "|\n") };
            return Json(formattedData);
        }

        /// <summary>
        /// Downloads the EDD message.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public FileResult DownloadEDDMessage()
        {
            string ImpersonatedUser = ConfigurationManager.AppSettings.Get("User");
            string ImpersonatedUserPassword = ConfigurationManager.AppSettings.Get("Password");
            string ImpersonatedUserDomain = ConfigurationManager.AppSettings.Get("Domain");

            string clientPath = ConfigurationManager.AppSettings.Get("TargetFolder")
                    + HttpContext.Request.UserHostAddress;
            string storagePath = clientPath + "\\EDDMessages";
            string zipTo = storagePath + ".zip";
            string downloadName = this.logDataModel.PolicyId + ".zip";

            using (UserImpersonation user = new UserImpersonation(ImpersonatedUser, ImpersonatedUserDomain, ImpersonatedUserPassword))
            {
                if (user.ImpersonateValidUser())
                {
                    HelperClass.CreateDirectory(clientPath);
                    HelperClass.CreateDirectory(storagePath);

                    foreach (EDDIORow row in this.logDataModel.EddKeys)
                    {
                        this.logDataModel.EddKey = string.Format("{0}-{1}", row.TRANSACTION_TIME, row.IO_CHAR);
                        string EDDMessage = this.CreateEDDMessage().Replace("|", "|\r\n");
                        string filename = ConfigurationManager.AppSettings.Get("TargetFolder")
                            + HttpContext.Request.UserHostAddress
                            + string.Format("\\EDDMessages\\{0} {1}-{2}-{3}.txt", this.logDataModel.PolicyId,
                            row.TRANSACTION_TIME.Replace("/", "-").Replace(":", "-"),
                            row.MSG_ID, string.Equals(row.IO_CHAR, "I") ? "Input" : "Output");

                        using (StreamWriter writer = new StreamWriter(filename, false))
                        {
                            writer.WriteLine(EDDMessage);
                            writer.Close();
                        }
                    }



                    using (ZipFile zip = new ZipFile())
                    {
                        zip.AddDirectory(storagePath);
                        zip.Save(zipTo);
                    }
                }
            }
            return File(zipTo, "application/zip", downloadName);
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetEDDMessageColAndTab()
        {
            this.vm = new EDDViewModel();
            vm.EddKey = this.logDataModel.EddKey;
            this.GetLOBCode();

            if (string.Equals(vm.MasterCompanyNbr, "02"))
            {
                return this.DataNotFound("Unable to find mapping for IB Policy.");
            }
            List<string> spliteEDDMessage = this.CreateEDDMessage().Split('|').ToList();
            this.GetPolarisIds();
            List<DataRow> polarisData = this.GetPolirisData();
            string eddMessageWithTableColumn = string.Empty;

            spliteEDDMessage.ForEach(
                message =>
                {
                    string strEDDMessageRow = string.Format("<span class='eddMessage'>{0}</span>", message);
                    polarisData.ForEach(dr =>
                    {
                        if (message.Contains(dr.Field<string>("POLARIS_ID")))
                        {
                            strEDDMessageRow += string.Format("<span class='eddTabCol'><span class='eddTable'>{0}</span><span class='eddColumn'>{1}</span></span>", dr.Field<string>("TABLE_NAME").Trim(), dr.Field<string>("COLUMN_NAME").Trim());
                        }
                    });
                    eddMessageWithTableColumn += "<span class='eddRow'><span class='eddMTC'>" + strEDDMessageRow + "</span></span>";
                });

                var formattedData = new { EDDMessage = eddMessageWithTableColumn };
                return Json(formattedData);
        }

        /// <summary>
        /// Creates the EDDIO rows.
        /// </summary>
        /// <param name="vm">The vm.</param>
        /// <returns>EDD IO Rows</returns>
        private List<EDDIORow> CreateEDDIORows()
        {
            List<EDDIORow> eDDIORow = null;
            vm.SqlQuery = ConfigurationManager.AppSettings["TXAMDETQuery"];
            Mapper.MapEDDInitialDataToDataModel(vm, this.logDataModel);
            GetExceedData.GetEddDetails(this.logDataModel);
            if (this.logDataModel.dataSet.Tables["Formatted_TXAMDET"] != null && this.logDataModel.dataSet.Tables["Formatted_TXAMDET"].AsEnumerable() != null)
            {
                eDDIORow = new List<EDDIORow>();
                var formattedTXAMDET = this.logDataModel.dataSet.Tables["Formatted_TXAMDET"].AsEnumerable();
                var keyData = (from row in formattedTXAMDET select new { TRANSACTION_TIME = row.Field<string>("TRANSACTION_TIME"), MSG_ID = row.Field<string>("MSG_ID"), IO_CHAR = row.Field<string>("IO_CHAR") }).ToList();
                string Message_ID = string.Empty;
                keyData.ForEach(row => {
                    Message_ID = HelperClass.GetExceedTransaction(row.MSG_ID);
                    eDDIORow.Add(new EDDIORow { TRANSACTION_TIME = row.TRANSACTION_TIME, MSG_ID = Message_ID, IO_CHAR = row.IO_CHAR });
                });
            }
            return eDDIORow;
        }

        /// <summary>
        /// Gets the policy ID from policy number.
        /// </summary>
        /// <param name="vm">The vm.</param>
        /// <returns>Returns Policy ID.</returns>
        private string GetPolicyIDFromPolicyNumber()
        {
            string PolicyId = string.Empty;
            vm.SqlQuery = ConfigurationManager.AppSettings["POLICYTABQuery"];
            Mapper.MapEDDInitialDataToDataModel(vm, this.logDataModel);

Live.Log.Extractor.Web/Views/Shared/Results.cshtml
@model Live.Log.Extractor.Web.Models.IndexModel
@using Live.Log.Extractor.Domain
<div id="ResultMessage">
@if (IsPost)
{
        <h3>@Model.ResultMessage</h3>
}

@if (Model.Results != null && Model.Results.Count > 0 && !Model.ErrorOrAbortCheck)
{
    <div class="serviceLogs">
            <span class="download" style="width:30%">@Html.ActionLink("Download log file", "Download", "Echannel", new { @class = "button bigrounded green" })</span>
            <h4>EChannel Service Logs</h4>
        <div id="serviceList">
            @foreach (EchannelLog log in Model.Results)
            {
                <span class="eddtio">@log.ServiceName - @log.LogDate.ToShortDateString() - @log.TimeStamp - @log.SessionID</span>
            }
        </div>
    </div>
}
else
{ 
    <span class="serviceLogs">No result found for your request.</span>
}
</div>           
<p>@ViewBag.PerformanceMonitor</p>

Live.Log.Extractor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.json2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.signalR.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftAjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/MicrosoftMvcAjax.js")" type="text/javascript"></script>
    @RenderSection("barChart", false)
</head>
<body>
    <div id="mainContainer">
        <div id="header">
            @{Html.RenderAction("Summary", "Cart");}
            <div class="title">
                <img src="@Url.Content("~/Content/images/logo.png")" alt="ApSelf"/> <span class="tagline">- Aviva Personal Systems Error Log Finder</span></div>
        </div>
        <div style="width: 100%; height: 8px; float: left;">
            <div style="width: 39%; height: 8px; float: left; background-color: #FFCC66;">
            </div>
            <div style="width: 61%; height: 8px; float: left; background-color: #549635;">
            </div>
        </div>
            <div id="categories">
            <div class="menu">
                <ul id="saturday">
                    <li>@Html.ActionLink("Home", "Welcome", "Login")</li>
                    <li>@Html.ActionLink("Exceed Logs", "Index", "Exceed")</li>
                    <li>@Html.ActionLink("EDD Logs", "Index", "EDD")</li>
                    <li>@Html.ActionLink("Echannel Logs", "Index", "Echannel")</li>
                    <li>@Html.ActionLink("Print Logs", "Index", "Print")</li>
                </ul>
                </div>
            </div>
             <div id="mainContent">
            <div id="content">
                @RenderBody()
            </div>
        </div>
		<!--div class="footer"><hr /><br />&copy; 2012 CSC </div-->
    </div>
</body>
</html>